name: snap_share
description: "Social Media App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  animated_custom_dropdown: ^3.1.1
  flutter_svg: ^2.0.16
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  photo_manager: ^3.6.3
  get: ^4.6.6
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  image_picker: ^1.1.2
  widget_and_text_animator: ^1.1.5
  lottie: ^3.1.3
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  cached_network_image: ^3.4.1
  salomon_bottom_bar: ^3.3.2
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/


  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Lobster
      fonts:
       - asset: assets/fonts/Lobster-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
