// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcWZo9MPQDJQrPDp3YlMpIb_3R7eP9G2I',
    appId: '1:56383975934:android:dbcbd79de705945b3250af',
    messagingSenderId: '56383975934',
    projectId: 'chit-chat-118c1',
    databaseURL:
        'https://chit-chat-118c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chit-chat-118c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS86z_fDdYWwM0HmMqG1tABCHsEw3y5gA',
    appId: '1:56383975934:ios:a74ca510cb0b62573250af',
    messagingSenderId: '56383975934',
    projectId: 'chit-chat-118c1',
    databaseURL:
        'https://chit-chat-118c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chit-chat-118c1.appspot.com',
    androidClientId:
        '56383975934-t96cu554e7e1lv3smcka28g2gfj5dcar.apps.googleusercontent.com',
    iosBundleId: 'com.sabt.snapShare',
  );
}
